### ISSUE TITLE
Error authorizing security group egress rules: InvalidParameterValue: Only Amazon VPC security groups may be used with this operation.

### ISSUE THREAD

**Issue by SrdjanStevanetic** [interchainio/testnets#14]
Dear all,

I am trying to set up the testnets for testing on AWS, and I run into the following issue (please see below). I would be very thankful to you if you could provide me some help regarding to this.
Many thanks!

```
(venv) srdjan@srdjan-VirtualBox:~/testnets$ ./tmtestnet.py -c mytestnets/testnet1.yaml -v network deploy
2020-03-31 09:31:55,628	DEBUG	Parsed environment variable: SIGNALFX_API_TOKEN
2020-03-31 09:31:55,628	DEBUG	Parsed environment variable: SIGNALFX_REALM
2020-03-31 09:31:55,628	DEBUG	Parsed environment variable: INFLUXDB_PASSWORD
2020-03-31 09:31:55,629	INFO	Config path is: /home/srdjan/testnets/mytestnets
2020-03-31 09:31:55,631	DEBUG	Wrote configuration to /home/srdjan/.tmtestnet/testnet_abcd/monitoring/terraform-extra-vars.yaml
2020-03-31 09:31:55,631	INFO	Deploying Grafana/InfluxDB monitoring
2020-03-31 09:31:55,631	DEBUG	Using InfluxDB password: ***********************c498r34n98cr
2020-03-31 09:31:55,632	INFO	Executing command: ansible-playbook -e @/home/srdjan/.tmtestnet/testnet_abcd/monitoring/terraform-extra-vars.yaml ansible-terraform.yaml

[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [127.0.0.1] *************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Apply Terraform service configuration] *********************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "command": "/home/srdjan/terraform/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmpe77crxh8.tfplan", "msg": "Failure when executing Terraform command. Exited 1.\nstdout: aws_security_group.monitor_sg: Destroying... [id=sg-06c9f3c111ed609e9]\naws_security_group.monitor_sg: Destruction complete after 2s\naws_security_group.monitor_sg: Creating...\n\nWarning: Quoted references are deprecated\n\n  on main.tf line 54, in data \"aws_region\" \"current\":\n  54:     provider = \"aws\"\n\nIn this context, references are expected literally rather than in quotes.\nTerraform 0.11 and earlier required quotes, but quoted references are now\ndeprecated and will be removed in a future version of Terraform. Remove the\nquotes surrounding this reference to silence this warning.\n\n(and 2 more similar warnings elsewhere)\n\n\nWarning: Interpolation-only expressions are deprecated\n\n  on main.tf line 60, in resource \"aws_instance\" \"monitor\":\n  60:     instance_type   = \"${var.instance_type}\"\n\nTerraform 0.11 and earlier required all non-constant expressions to be\nprovided via interpolation syntax, but this pattern is now deprecated. To\nsilence this warning, remove the \"${ sequence from the start and the }\"\nsequence from the end of this expression, leaving just the inner expression.\n\nTemplate interpolation syntax is still used to construct strings from\nexpressions when the template includes multiple interpolation sequences or a\nmixture of literal strings and interpolations. This deprecation applies only\nto templates that consist entirely of a single interpolation sequence.\n\n(and one more similar warning elsewhere)\n\n\nstderr: \nError: Error authorizing security group egress rules: InvalidParameterValue: Only Amazon VPC security groups may be used with this operation.\n\tstatus code: 400, request id: cf83781b-9792-4d19-8b40-77e75886afd5\n\n  on main.tf line 86, in resource \"aws_security_group\" \"monitor_sg\":\n  86: resource \"aws_security_group\" \"monitor_sg\" {\n\n\n"}

PLAY RECAP *******************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


2020-03-31 09:32:22,082	ERROR	Failed to execute "network deploy" for configuration file: mytestnets/testnet1.yaml
2020-03-31 09:32:22,083	ERROR	Process failed with return code 2
Traceback (most recent call last):
  File "./tmtestnet.py", line 392, in tmtestnet
    fn(cfg, **kwargs)
  File "./tmtestnet.py", line 420, in network_deploy
    monitoring_outputs = terraform_deploy_monitoring(
  File "./tmtestnet.py", line 1005, in terraform_deploy_monitoring
    sh([
  File "./tmtestnet.py", line 1571, in sh
    raise Exception("Process failed with return code %d" % p.returncode)
Exception: Process failed with return code 2
```

**Comment by SrdjanStevanetic** [comment]
Hi all,

I have did some progress. I have removed the egress rule, and introduced vpc_security_group_ids in the monitor/main.tf file for the resource "aws_instance" "monitor". This launched successfully the instance in my aws account. Now I have some other problem, actually the error is about some SSH keys:
```
2020-04-01 16:00:36,649	INFO	Monitoring successfully deployed
2020-04-01 16:00:36,651	DEBUG	Removing any existing keys for host: 
2020-04-01 16:00:37,654	DEBUG	Scanning keys for host: 
2020-04-01 16:00:38,660	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:00:43,665	DEBUG	Scanning keys for host: 
2020-04-01 16:00:44,673	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:00:49,680	DEBUG	Scanning keys for host: 
2020-04-01 16:00:50,690	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:00:55,696	DEBUG	Scanning keys for host: 
2020-04-01 16:00:56,706	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:01,713	DEBUG	Scanning keys for host: 
2020-04-01 16:01:02,721	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:07,727	DEBUG	Scanning keys for host: 
2020-04-01 16:01:08,734	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:13,740	DEBUG	Scanning keys for host: 
2020-04-01 16:01:14,750	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:19,757	DEBUG	Scanning keys for host: 
2020-04-01 16:01:20,766	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:25,768	DEBUG	Scanning keys for host: 
2020-04-01 16:01:26,774	WARNING	ssh-keyscan failed with return code 0 and 0 keys - trying again in 5 seconds
2020-04-01 16:01:31,781	DEBUG	Scanning keys for host: 
2020-04-01 16:01:32,788	ERROR	Failed to execute "network deploy" for configuration file: mytestnets/testnet1.yaml
2020-04-01 16:01:32,790	ERROR	Call to ssh-keyscan failed with return code 0
Traceback (most recent call last):
  File "./tmtestnet.py", line 392, in tmtestnet
    fn(cfg, **kwargs)
  File "./tmtestnet.py", line 420, in network_deploy
    monitoring_outputs = terraform_deploy_monitoring(
  File "./tmtestnet.py", line 1015, in terraform_deploy_monitoring
    ensure_in_known_hosts(output_vars["host"]["public_dns"])
  File "./tmtestnet.py", line 1873, in ensure_in_known_hosts
    host_keys = get_host_keys(hostname)
  File "./tmtestnet.py", line 1849, in get_host_keys
    raise Exception("Call to ssh-keyscan failed with return code %d" % p.returncode)
Exception: Call to ssh-keyscan failed with return code 0
```

Do you have any idea what this can be? I am really trying to bring this to work for several days.
Many thanks!

Srdjan

**Comment by SrdjanStevanetic** [comment]
I have resolved this as well by enabling DNS related things in my VPC. I am currently trying to watch the metrics in grafana. I have configured a Data Source to be the influx DB but I cannot figure out how to find tendermint metrics there. Many thanks!

**Comment by SrdjanStevanetic** [comment]
I am closing this issue.
